# Generated by Django 5.2.14 on 2026-05-24 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', help_text='Nombre de la empresa o negocio', max_length=200)),
                ('business_address', models.TextField(blank=True, default='', help_text='Dirección del negocio')),
                ('tax_id', models.CharField(blank=True, help_text='Número de identificación fiscal', max_length=50, null=True, unique=True)),
                ('phone', models.CharField(blank=True, default='', help_text='Teléfono de contacto del negocio', max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='Indica si el dueño ha sido verificado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Usuario asociado al perfil de dueño', on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dueño',
                'verbose_name_plural': 'Dueños',
                'db_table': 'owner',
                'ordering': ['company_name'],
                'indexes': [models.Index(fields=['user'], name='owner_user_id_92a1d3_idx'), models.Index(fields=['tax_id'], name='owner_tax_id_8f4ff1_idx'), models.Index(fields=['company_name'], name='owner_company_d74bc9_idx')],
            },
        ),
    ]
